version: "3"
services: 
    prism:
        image: stoplight/prism:3
        ports:
            - "4010:4010"
        volumes:
            - ./:/tmp
        command: >
            mock -h 0.0.0.0 "/tmp/openapi.yaml"
    lint:
        image: wework/speccy
        volumes:
            - ./:/tmp
        command: >
            lint /tmp/openapi.yaml
    resolve:
        image: wework/speccy        
        volumes:
            - ./:/tmp
        command: >
            resolve -o /tmp/openapi.yaml /tmp/api/root.yaml
    serve:
        image: wework/speccy
        ports: 
            - "5000:5000"
        volumes: 
            - ./:/tmp
        command: >
            serve /tmp/openapi.yaml

